# Setup Jogo

## Instalar Gym-Retro e Bibliotecas Necessarias

In [ ]:
#!pip install gym==0.19.0 gym-retro 

In [ ]:
#!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

In [ ]:
# No prompt da anaconda ative o venv que ira utilizar, exemplo: "conda activate envtest". Apos ativar entre na sua pasta roms (com a ROM do jogo dentro dessa pasta) e execute o comando abaixo.
# python -m retro.import .

In [ ]:
#!pip install opencv-python

In [ ]:
#!pip install ipywidgets 

In [ ]:
#!pip install stable-baselines3[extra]==1.3.0 optuna --user

In [1]:
#python < 3.8 
#Verifique que o python esta entre a versao 3.7 e 3.8 pois o gym retro so funciona nessas versoes
import sys
sys.version


'3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]'

## Importar Dependencias

In [2]:
#importando retro para usar MK ROM
import retro
# Sera usado para diminuir velocidade do jogo
import time

import os

In [3]:
#Se erro do tipo ja existe um env aberto rodar esse codigo
env.close()

NameError: name 'env' is not defined

In [4]:
#Inicia jogo
env = retro.make(game='MortalKombatII-Genesis')
#env.reset()


In [5]:
# Verificando se o observation space esta funcionando
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [6]:
# Verificando se o action space esta funcionando
env.action_space.sample()

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int8)

# Setup env
Vamos otimizar removendo as cores (agente nao precisa ver cores) e diminuir observation space do agente

In [7]:
from gym import Env 
from gym.spaces import MultiBinary, Box
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [9]:
class MortalKombat(Env):
    def __init__(self):
        super().__init__()
        self.observation_space = Env.observation_space
        self.observation_space = Box(low=0, high=255, shape=(84, 84, 1), dtype = np.uint8) #O que o agente "ve"
        self.action_space = MultiBinary(12) # O que o agente pode fazer (acoes)
        #self.game = retro.make(game='MortalKombatII-Genesis', obs_type='image', use_restricted_actions=retro.Actions.FILTERED) # retro.Actions.FILTERED nos da somente acoes validas
        self.game = retro.make(game='MortalKombatII-Genesis', use_restricted_actions=retro.Actions.FILTERED, players=2) # retro.Actions.FILTERED nos da somente acoes validas
        #env = retro.make(gamename, state='firstfightveryeasy.state', obs_type=retro.Observations.IMAGE)
        #self.game.reset()
    def reset(self):
        #Recomeca jogo
        obs = self.game.reset()
        obs = self.preprocess(obs)
        self.previous_frame=obs
        
        # Infos (guardar o score a cada frame)
        self.score = 0
        return obs
    
    def render(self, *args, **kwargs):
        self.game.render()
    
    def close(self):
        self.game.close()
        
    
    #Vamos transformar o jogo em cinza e diminuir o tamanho 
    def preprocess(self, observation):
        #Transforma em cinza
        cinza = cv2.cvtColor(observation, cv2.COLOR_BGR2GRAY)
        #Resize
        resize = cv2.resize(cinza, (84,84), interpolation = cv2.INTER_CUBIC)
        final = np.reshape(resize, (84,84,1))
        return final
        
    def step(self, action):
        obs, reward, done, info = self.game.step(action)
        obs = self.preprocess(obs) #Otimizacoes comentadas acimas...
        
        frame_change = obs - self.previous_frame #Pixels que mudaram do ultimo frame para o novo
        self.previous_frame = obs
        
        #Reward (depois mudar os parametros)
        reward = info['rounds_won']*500 + info['enemy_rounds_won']*-500 + info['health']*1 + info['enemy_health']*-1 - self.score
        
        self.score = info['rounds_won']*500 + info['enemy_rounds_won']*-500 + info['health'] + info['enemy_health']*-1
    
        return frame_change, reward, done, info
        
    

In [10]:
env.close()
env = MortalKombat()
#env.reset()
    

In [11]:
# IA faz movimento aleatorios nesse teste
obs = env.reset()
dead = False
for game in range(1): 
    while not dead: 
        if dead: 
            obs = env.reset()
        env.render()
        obs, reward, dead, info = env.step(env.action_space.sample())
        time.sleep(0.01) 
        print(reward)

E:\Anaconda\envs\python37\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Não é possível alterar o modo de thread depois de o mesmo estar definido
  warnings.warn(str(err))


0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-15
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
24
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

# Hiperparametros & Optuna

In [12]:
import torch

if torch.cuda.is_available():
    print("CUDA está disponível!")
    print("Versão do CUDA:", torch.version.cuda)
else:
    print("CUDA não está disponível.")



CUDA está disponível!
Versão do CUDA: 11.7


In [13]:
import stable_baselines3

print(stable_baselines3.__version__)


1.3.0


In [14]:
# Metodos e bibliotecas que utilizaremos
import optuna
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import VecTransposeImage
from stable_baselines3.common.callbacks import BaseCallback
from gym.wrappers import FrameStack
from gym.wrappers import FrameStack


In [15]:
LOG_D = './logs/'
OPT_D= './opt/'
# Vamos salvar o resultados do Optuna nesse path
PATH = os.path.join(OPT_D, 'v_{}_best_model_'.format(1)) 

In [16]:
PATH

'./opt/v_1_best_model_'

In [17]:
#Usado pelo optuna para sugerir um valor para os hiperparametros
#Valores sugeridos 
def opt_objective(trial): 
    return {
        'n_steps':trial.suggest_int('n_steps', 2048, 8192),
        'gamma':trial.suggest_float('gamma', 0.8, 0.9999),
        'learning_rate':trial.suggest_float('learning_rate', 1e-5, 1e-4),
        'clip_range':trial.suggest_float('clip_range', 0.1, 0.4),
        'gae_lambda':trial.suggest_float('gae_lambda', 0.8, 0.99)
    }

In [18]:
def optimize_agent(trial):
    try:
        parametros = opt_objective(trial) # Pegamos valores para os hiperparametros da funcao testamos

        env = MortalKombat()
        #Monitora o env para depois podermos visualizar como as configuracoes de hiperparametros se sairam
        env = Monitor(env, LOG_D)
        env = DummyVecEnv([lambda: env])
        #env = CustomDummyVecEnv([lambda: env])
        # Nosso MDPs tera 4 frames de "memoria" para tomar a proxima decisao
        env = VecFrameStack(env, n_stack=4, channels_order='last')
        #env = FrameStack(env, 4)
        #env = VecTransposeImage(env)

        ppo_mod = PPO('CnnPolicy', env, tensorboard_log=LOG_D, verbose=0, **parametros) #utilizamos o PPO para resolver o MDPs
        ppo_mod.learn(total_timesteps=100000)
        #model.learn(total_timesteps=100)

        reward_mean, _ = evaluate_policy(ppo_mod, env, n_eval_episodes=5) #n_eval_episodes é em quantos jogos essa configuracao sera testada
        env.close()

        PATH = os.path.join(OPT_D, 'v_{}_best_model'.format(trial.number))
        ppo_mod.save(PATH)

        return reward_mean 

    except Exception as e: #Algumas configuracoes de hiperparametros podem nao funcionar por isso a try
        return -100000

In [19]:
env.close() #Para fechar um env caso esteja aberto

In [ ]:
#Realizando o estudo de hiperparametros
study = optuna.create_study(direction='maximize') #Por default o optuna tenta minimizar a funcao
#study.optimize(optimize_agent, n_trials=100, n_jobs=1) 
study.optimize(optimize_agent, n_trials=15, n_jobs=1)

In [ ]:
number_x = study.best_trial.number
#print(number_x)
path_v_best_model = 'v_{}_best_model'.format('number_x')
#path_v_best_model = 'v_{}_best_model.zip'.format('100')
best_model = PPO.load(os.path.join(OPT_D, path_v_best_model))
print(path_v_best_model)

# Treinamento

In [ ]:
# Classe padrao baseada no callback da documentacao do stable baselines: https://stable-baselines.readthedocs.io/en/master/guide/callbacks.html
class CustomCallback(BaseCallback):

    def __init__(self, check_freq, save_path, verbose=1):
        super(CustomCallback, self).__init__(verbose)
        self.check_freq = check_freq
        self.save_path = save_path

    def _init_callback(self):
        if self.save_path is not None:
            os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self):
        if self.n_calls % self.check_freq == 0:
            best_model_path = os.path.join(self.save_path, 'best_model_{}'.format(self.n_calls))
            self.model.save(best_model_path)

        return True

In [ ]:
TRAIN_D = './train/'

In [ ]:
callback = CustomCallback(check_freq=10000, save_path=TRAIN_D)

In [ ]:
env.close()

In [ ]:

env = MortalKombat()
env = Monitor(env, LOG_D)
env = DummyVecEnv([lambda: env])
env = VecFrameStack(env, n_stack=4)



In [ ]:
best_model_param = study.best_params
best_model_param['n_steps'] = ((best_model_param['n_steps'] + 63) // 64) * 64 #tornando o n_steps divisivel por 64
best_model_param


In [ ]:
#Caso queira usar valores pre definidos

best_model_param['n_steps']=2560
best_model_param['gamma'] = 0.9061171556168366
best_model_param['learning_rate'] = 6.460301413190717e-07
#best_model_param['clip_range'] =
best_model_param['gae_lambda'] = 0.8912571976783701

In [ ]:
ppo_model = PPO('CnnPolicy', env, tensorboard_log=LOG_D, verbose=1, **best_model_param) #utilizamos o PPO para resolver o MDPs


In [ ]:
ppo_model.load(os.path.join(OPT_D, path_v_best_model))

In [ ]:
ppo_model.learn(total_timesteps=100000, callback=callback)

# Avaliar Modelos Treinados

In [ ]:
path_train = './train/best_model_200000.zip'
ppo_model = PPO.load(path_train)

In [ ]:
mean_score, _ = evaluate_policy(ppo_model, env, n_eval_episodes=5, render=True)

# Testes

In [ ]:
obs = env.reset()
dead = False
for game in range(1): 
    while not dead: 
        if dead: 
            obs = env.reset()
        env.render()
        predict = ppo_model.predict(obs)[0]
        obs, reward, dead, info = env.step(predict)
        time.sleep(0.01) 
        print(reward)